/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [9.83KB] > C:\Users\Mae K\OneDrive - nevada.unr.edu\Documents\2023-2024\Winter 2024\IrvineHacks 2024\my-app\public\Pandahead\scene-transformed.glb [192.33KB] (-1857%)
Author: gaoran0623 (https://sketchfab.com/gaoran0623)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/panda-head-meme-726745400b4d44128016f4280c313a3d
Title: Panda head meme
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Pandahead(props) {
  const { nodes, materials } = useGLTF('/Pandahead/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <ambientLight intensity={3} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[0.053, 0.022, 0]} rotation={[3.031, 0, Math.PI]} scale={0.844} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.black} position={[0, -0.804, -0.826]} rotation={[0.151, 0, 0]} scale={[1.366, 1.507, 1.252]} />
    </group>
  )
}

useGLTF.preload('/Pandahead/scene-transformed.glb')
