/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [23.71KB] > C:\Users\Mae K\OneDrive - nevada.unr.edu\Documents\2023-2024\Winter 2024\IrvineHacks 2024\my-app\public\Goose\scene-transformed.glb [34.52KB] (-46%)
Author: Bianca.Popa (https://sketchfab.com/Bianca.Popa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/goose-with-knife-fdc0d2f24a4c422dba503f2b9f445e24
Title: goose with knife
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Goose(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Goose/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <ambientLight intensity={3} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_9.skeleton} position={[-0.333, 0.82, -2.833]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={5.152} />
        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_10.skeleton} position={[-0.333, 0.82, -2.833]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={5.152} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_11.skeleton} position={[-0.333, 0.82, -2.833]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={5.152} />
        <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_12.skeleton} position={[-0.333, 0.82, -2.833]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={5.152} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_13.skeleton} position={[-0.333, 0.82, -2.833]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={5.152} />
      </group>
    </group>
  )
}

useGLTF.preload('/Goose/scene-transformed.glb')
