/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [143.44KB] > C:\Users\Mae K\OneDrive - nevada.unr.edu\Documents\2023-2024\Winter 2024\IrvineHacks 2024\my-app\public\Ucat\scene-transformed.glb [101.15KB] (29%)
Author: fovlaxcorp (https://sketchfab.com/fovlaxcorp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ucat-cat-or-cat-de41bd91bcdb4a70a412c377bff03388
Title: Ucat (ЪУЪ Cat or ЪЫЪ Cat)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Ucat(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Ucat/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <ambientLight intensity={3} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Material.002']} skeleton={nodes.Object_7.skeleton} position={[0, 0.359, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Ucat/scene-transformed.glb')
